### ISSUE TITLE
psroi_pooling.so not find

### ISSUE THREAD

**Issue by q2442590777** [walsvid/Faster-RCNN-TensorFlow#14]
(tfgpu) root@00300ef242a2:/workspace/Faster-RCNN-TensorFlow# python ./tools/demo.py -- model ./tools/model/VGGnet_fast_rcnn_iter_70000.ckpt 
Traceback (most recent call last):
  File "./tools/demo.py", line 13, in <module>
    from networks.factory import get_network
  File "/workspace/Faster-RCNN-TensorFlow/tools/../lib/networks/__init__.py", line 8, in <module>
    from .VGG16 import VGG16
  File "/workspace/Faster-RCNN-TensorFlow/tools/../lib/networks/VGG16.py", line 2, in <module>
    from networks.network import Network
  File "/workspace/Faster-RCNN-TensorFlow/tools/../lib/networks/network.py", line 5, in <module>
    import psroi_pooling_layer.psroi_pooling_op as psroi_pooling_op
  File "/workspace/Faster-RCNN-TensorFlow/tools/../lib/psroi_pooling_layer/psroi_pooling_op.py", line 5, in <module>
    _psroi_pooling_module = tf.load_op_library(filename)
  File "/root/envs/tfgpu/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/root/envs/tfgpu/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /workspace/Faster-RCNN-TensorFlow/tools/../lib/psroi_pooling_layer/psroi_pooling.so: cannot open shared object file: No such file or directory

How to solve excuse me

**Comment by walsvid** [comment]
I saw there is some error with `psroi_pooling.so` not found. Have you tried building a cython module according to the instructions of the README? 
```
ROOT =  the source code directory of Faster-RCNN-TensorFlow
cd ${ROOT}/lib
make
```

**Comment by walsvid** [comment]
I have this issue temporarily closed. If I can't solve your problem, I will re-open it.

**Comment by cbiras** [comment]
Hi, I'm facing the same issue. How did you solve it?

**Comment by walsvid** [comment]
Hi @cbiras , try to compile CUDA code.
