### ISSUE TITLE
KeyError: 'Unknown layer name fed: rpn_rois'

### ISSUE THREAD

**Issue by penbury** [walsvid/Faster-RCNN-TensorFlow#15]
when I want to run demp.py, it occurs that:

Traceback (most recent call last):
  File "/home/lt/workplace/pycharm/Faster-RCNN-TensorFlow-master/tools/demo.py", line 117, in <module>
    net = get_network(args.demo_net)
  File "/home/lt/workplace/pycharm/Faster-RCNN-TensorFlow-master/tools/../lib/networks/factory.py", line 25, in get_network
    net = __sets[name].setup()
  File "/home/lt/workplace/pycharm/Faster-RCNN-TensorFlow-master/tools/../lib/networks/VGG16.py", line 66, in setup
    (self.feed('rpn_rois', 'gt_boxes')
  File "/home/lt/workplace/pycharm/Faster-RCNN-TensorFlow-master/tools/../lib/networks/network.py", line 110, in feed
    raise KeyError('Unknown layer name fed: %s' % layer_name)
KeyError: 'Unknown layer name fed: rpn_rois'

**Comment by penbury** [comment]
I've solved by changed 'rpn_rois' to 'rois'.
